### ISSUE TITLE
Throws warning 

### ISSUE THREAD

**Issue by peterlindstrom** [kenshoo/react-multi-select#116] opened 2018-12-10 21:33 UTC
I see a warning thrown when using this component. It can be fixed upgrading prop-types to at least 15.5.10

## Actual Behavior
checkPropTypes.js?a15c:19 Warning: Failed prop type: Calling PropTypes validators directly is not supported by the `prop-types` package. Use PropTypes.checkPropTypes() to call them. Read more at http://fb.me/use-check-prop-types

## More info
https://github.com/malte-wessel/react-custom-scrollbars/issues/153#issuecomment-301098921

**Comment by liorheber** [comment] 2018-12-10 21:38
Thanks @peterlindstrom ,
Could you please share the full warning you're receiving (with stack trace)?
I'm looking at our demo site and I was unable to see any warning besides some Storybook build warnings.
[Demo](https://kenshoo.github.io/react-multi-select/)

**Comment by isabolic** [comment] 2018-12-17 09:53
Warning: Failed prop type: Calling PropTypes validators directly is not supported by the `prop-types` package. Use PropTypes.checkPropTypes() to call them. Read more at http://fb.me/use-check-prop-types
    in t (created by n)
    in n (created by Shuttle)
    in Shuttle (created by GroupForm)
    in div (created by GroupForm)
    in GroupForm (created by Connect(GroupForm))
    in Connect(GroupForm) (created by FirebaseConnect(Connect(GroupForm)))
    in FirebaseConnect(Connect(GroupForm)) (created by BikeGroupView)
    in div (created by SimpleGrid)
    in SimpleGrid (created by BikeGroupView)
    in div (created by Grid)
    in Grid (created by BikeGroupView)
    in div (created by Col)
    in Col (created by BikeGroupView)
    in div (created by Row)
    in Row (created by BikeGroupView)
    in div (created by Grid)
    in Grid (created by BikeGroupView)
    in BikeGroupView (created by Route)
    in Route (created by withRouter(BikeGroupView))
    in withRouter(BikeGroupView) (created by Connect(withRouter(BikeGroupView)))
    in Connect(withRouter(BikeGroupView)) (created by Route)
    in Route (created by App)
    in Switch (created by PageTransition)
    in div (created by PageTransition)
    in PageTransition (created by App)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by App)
    in div (created by App)
    in App (created by Route)
    in Route (created by withRouter(App))
    in withRouter(App)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Connect(ConnectedRouter))
    in Connect(ConnectedRouter)
    in Provider


  | printWarning | @ | checkPropTypes.js:19
-- | -- | -- | --
  | checkPropTypes | @ | checkPropTypes.js:82
  | validatePropTypes | @ | react.development.js:1649
  | createElementWithValidation | @ | react.development.js:1738
  | React$$1.createElement | @ | react-hot-loader.development.js:984
  | value | @ | index.js:24
  | hotComponentRender | @ | react-hot-loader.development.js:622
  | proxiedRender | @ | react-hot-loader.development.js:637
  | finishClassComponent | @ | react-dom.development.js:14301
  | updateClassComponent | @ | react-dom.development.js:14264
  | beginWork | @ | react-dom.development.js:15082
  | performUnitOfWork | @ | react-dom.development.js:17820
  | workLoop | @ | react-dom.development.js:17860
  | renderRoot | @ | react-dom.development.js:17946
  | performWorkOnRoot | @ | react-dom.development.js:18837
  | performWork | @ | react-dom.development.js:18749
  | performSyncWork | @ | react-dom.development.js:18723
  | interactiveUpdates$1 | @ | react-dom.development.js:18992
  | interactiveUpdates | @ | react-dom.development.js:2169
  | dispatchInteractiveEvent | @ | react-dom.development.js:4876




  | printWarning | @ | checkPropTypes.js:19
-- | -- | -- | --
  | checkPropTypes | @ | checkPropTypes.js:82
  | validatePropTypes | @ | react.development.js:1649
  | createElementWithValidation | @ | react.development.js:1738
  | React$$1.createElement | @ | react-hot-loader.development.js:984
  | value | @ | index.js:24
  | hotComponentRender | @ | react-hot-loader.development.js:622
  | proxiedRender | @ | react-hot-loader.development.js:637
  | finishClassComponent | @ | react-dom.development.js:14301
  | updateClassComponent | @ | react-dom.development.js:14264
  | beginWork | @ | react-dom.development.js:15082
  | performUnitOfWork | @ | react-dom.development.js:17820
  | workLoop | @ | react-dom.development.js:17860
  | renderRoot | @ | react-dom.development.js:17946
  | performWorkOnRoot | @ | react-dom.development.js:18837
  | performWork | @ | react-dom.development.js:18749
  | performSyncWork | @ | react-dom.development.js:18723
  | interactiveUpdates$1 | @ | react-dom.development.js:18992
  | interactiveUpdates | @ | react-dom.development.js:2169
  | dispatchInteractiveEvent | @ | react-dom.development.js:4876

**Comment by liorheber** [comment] 2018-12-17 12:24
I am unable to reproduce your issue in any environment.
We will upgrade prop-types in hopes that it assists you as it contains no risks to the package - later today.

Please let us know if this solves the issue or if we need to further investigate this.
If this reoccurs, could you please supply us with a reproducible example?

**Comment by liorheber** [comment] 2018-12-17 14:12
Latest prop-types was merged, please let us know if this indeed solved the issue.

**Comment by isabolic** [comment] 2018-12-18 06:48
Hi @liorheber ,

The issue is still present with the same message.

Best regards
isabolic

**Comment by talyak** [comment] 2018-12-18 12:37
@isabolic - Can you share with me reproducible code so I can see the issue and try to fix it accordingly?

**Comment by isabolic** [comment] 2018-12-18 12:41
```
import MultiSelect from '@kenshooui/react-multi-select';
import * as React from 'react';

class Shuttle extends React.PureComponent {
    constructor(props) {
        super(props);
        this.handleChange = this.handleChange.bind(this);
    }

    render() {
        return (
        <MultiSelect
            items={this.props.options}
            selectedItems={this.props.selected}
            onChange={this.handleChange}
        />
        );
    }

    handleChange(selected) {
       ...
    }
}

export default Shuttle;
```

**Comment by SoorajSethumadhavan** [comment] 2019-02-10 06:36
<img width="1232" alt="screenshot 2019-02-10 at 12 01 24 pm" src="https://user-images.githubusercontent.com/11325941/52530447-e7f5cc80-2d2b-11e9-9bed-7147a5361f46.png">


I'm a noobie in react! 
this is what I have in my package.json
"react": "^16.8.1",
"react-dom": "^16.8.1",

"react-redux": "^6.0.0",
 "redux": "^4.0.1",

**Comment by BaptWaels** [comment] 2019-03-11 13:19
Hi,

Any update on this issue ? 
I'm experiencing the same behaviour.

**Comment by liorheber** [comment] 2019-03-11 13:22
Hi @BaptWaels,
We investigated the issue and it seems related to react-height.
It's currently low on our priorities because it's only a warning and doesn't break the component.
I hope we can get to it as soon as possible but I also encourage trying to issue a fix to this if you have the capacity for it.

**Comment by asmithriscnetworks** [comment] 2019-03-28 18:33
Looked into the issue a little. A PR was approved which supposedly fixed the issue. On April 17th 2018 and a tag was pushed, `3.0.0`.  https://github.com/nkbt/react-height/pull/37

The npm page says the package has not been updated for 2 years but the release tag is listed the releases. 

Not sure wha'ts going on, but this package has the correctly `react-height` version (3.0.0), and a version of prop-types which should fix the issue. 

¯\_(ツ)_/¯

**Comment by Ektoplasme** [comment] 2019-04-10 11:53
The package has the correct react-height version but in this 3.0.0 in my package-lock.json, prop-types version is still 15.5.8 or it should be 15.5.10 to fix the issue
 
"react-height": {
      "version": "3.0.0",
      "resolved": "https://registry.npmjs.org/react-height/-/react-height-3.0.0.tgz",
      "integrity": "sha1-+uMi+dpk0+niVTbya3fHOVQmFSQ=",
      "requires": {
        "prop-types": "15.5.8"
      }

 > [https://github.com/facebook/prop-types/issues/38](url) last answer

**Comment by BaptWaels** [comment] 2019-04-11 12:36
I've created an issue on `react-height` to create a new release :
[#38](https://github.com/nkbt/react-height/issues/38)

**Comment by liorheber** [comment] 2019-04-15 18:44
Thank you @BaptWaels !

**Comment by liorheber** [comment] 2019-05-02 01:07
https://github.com/kenshoo/react-multi-select/pull/145 should solve the issue as we removed react-height dependency from the component.

**Comment by talyak** [comment] 2019-05-13 09:29
resolved

**Closed by talyak** 2019-05-13 09:29 UTC
